package com.android.sellacha.Order.Model

data class DataX(
    val answer1: Any,
    val answer2: Any,
    val answer3: Any,
    val answer4: Any,
    val answer5: Any,
    val attributes: List<Any>,
    val created_at: String,
    val featured: String,
    val id: Int,
    val is_admin: String,
    val options: List<Any>,
    val preview: Preview,
    val price: Price,
    val question1: Any,
    val question2: Any,
    val question3: Any,
    val question4: Any,
    val question5: Any,
    val service_location: Any,
    val service_type: Any,
    val slug: String,
    val status: String,
    val stock: Stock,
    val title: String,
    val type: String,
    val updated_at: String,
    val user_id: String,
    val youtube_link: Any
)