package com.android.sellacha.Profile.model

data class Data(
    val `2fa_auth`: Any,
    val `2fa_auth_login`: Any,
    val `2fa_auth_send`: Any,
    val `2fa_auth_withdrawal`: Any,
    val account_level: Any,
    val account_type: Any,
    val account_user: Any,
    val address:String?=null,
    val birthday_date: Any,
    val business_category: Any,
    val business_country: Any,
    val business_description: Any,
    val business_name: Any,
    val business_reject: Any,
    val business_status: Any,
    val business_website: Any,
    val business_who_pay_fee: Any,
    val city:String?=null,
    val country: Any,
    val created_at: String,
    val created_by: Any,
    val document_verified: Any,
    val domain_id: String,
    val email: String,
    val email_hash: Any,
    val email_verified: Any,
    val email_verified_at: Any,
    val first_name: String?=null,
    val googlecode: Any,
    val id: Int,
    val ip:String?=null,
    val ispur: String,
    val last_login: Any,
    val last_name: String?=null,
    val membership: Any,
    val merchant_api_key: Any,
    val mob: String?=null,
    val mobile:  String?=null,
    val name:String?=null,
    val password_recovery: Any,
    val plnt: Any,
    val province: Any,
    val ref1: Any,
    val role_id: String,
    val sertype: String,
    val shop_type: String,
    val signup_time: Any,
    val status: String,
    val u_type: String,
    val updated_at: String,
    val veri: String,
    val video_link: String,
    val wallet_passphrase: Any,
    val zip_code: Any
)